export const mockResponse = [
  {
    adult: false,
    backdrop_path: '/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg',
    genre_ids: [27, 53],
    id: 980078,
    original_language: 'en',
    original_title: 'Winnie the Pooh: Blood and Honey',
    overview:
      'Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.',
    popularity: 3800.257,
    poster_path: '/wtFwgFFk1ze789ghcadWGEVjj3N.jpg',
    release_date: '2023-01-27',
    title: 'Winnie the Pooh: Blood and Honey',
    video: false,
    vote_average: 5.9,
    vote_count: 205
  },
  {
    adult: false,
    backdrop_path: '/a2tys4sD7xzVaogPntGsT1ypVoT.jpg',
    genre_ids: [53, 35, 80],
    id: 804150,
    original_language: 'en',
    original_title: 'Cocaine Bear',
    overview:
      'Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.',
    popularity: 3474.498,
    poster_path: '/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg',
    release_date: '2023-02-22',
    title: 'Cocaine Bear',
    video: false,
    vote_average: 6.5,
    vote_count: 506
  },
  {
    adult: false,
    backdrop_path: '/ovM06PdF3M8wvKb06i4sjW3xoww.jpg',
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: 'en',
    original_title: 'Avatar: The Way of Water',
    overview:
      'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
    popularity: 3464.178,
    poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    release_date: '2022-12-14',
    title: 'Avatar: The Way of Water',
    video: false,
    vote_average: 7.7,
    vote_count: 5982
  },
  {
    adult: false,
    backdrop_path: '/i8dshLvq4LE3s0v8PrkDdUyb1ae.jpg',
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: 'en',
    original_title: 'John Wick: Chapter 4',
    overview:
      'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
    popularity: 3361.154,
    poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
    release_date: '2023-03-22',
    title: 'John Wick: Chapter 4',
    video: false,
    vote_average: 8.2,
    vote_count: 384
  },
  {
    adult: false,
    backdrop_path: '/ouB7hwclG7QI3INoYJHaZL4vOaa.jpg',
    genre_ids: [16, 12, 35, 10751],
    id: 315162,
    original_language: 'en',
    original_title: 'Puss in Boots: The Last Wish',
    overview:
      'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
    popularity: 1862.289,
    poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
    release_date: '2022-12-07',
    title: 'Puss in Boots: The Last Wish',
    video: false,
    vote_average: 8.3,
    vote_count: 4854
  },
  {
    adult: false,
    backdrop_path: '/2Eewgp7o5AU1xCataDmiIL2nYxd.jpg',
    genre_ids: [18, 36],
    id: 943822,
    original_language: 'en',
    original_title: 'Prizefighter: The Life of Jem Belcher',
    overview:
      'At the turn of the 19th century, Pugilism was the sport of kings and a gifted young boxer fought his way to becoming champion of England.',
    popularity: 1635.927,
    poster_path: '/x3PIk93PTbxT88ohfeb26L1VpZw.jpg',
    release_date: '2022-06-30',
    title: 'Prizefighter: The Life of Jem Belcher',
    video: false,
    vote_average: 6.2,
    vote_count: 92
  },
  {
    adult: false,
    backdrop_path: '/sp7MPK2K60LLd7A6zjHKsfgjFil.jpg',
    genre_ids: [27, 53],
    id: 296271,
    original_language: 'en',
    original_title: 'The Devil Conspiracy',
    overview:
      'The hottest biotech company in the world has discovered they can clone history’s most influential people from the dead. Now, they are auctioning clones of Michelangelo, Galileo, Vivaldi, and others for tens of millions of dollars to the world’s ultra-rich. But when they steal the Shroud of Turin and clone the DNA of Jesus Christ, all hell breaks loose.',
    popularity: 1538.468,
    poster_path: '/AnpRLu2zTa0yJWVxyYxUnNg0zvX.jpg',
    release_date: '2023-01-13',
    title: 'The Devil Conspiracy',
    video: false,
    vote_average: 6.5,
    vote_count: 58
  },
  {
    adult: false,
    backdrop_path: '/zM9RGbJBZ3UNpFOabcRqh0iVAYP.jpg',
    genre_ids: [27, 9648, 53],
    id: 631842,
    original_language: 'en',
    original_title: 'Knock at the Cabin',
    overview:
      'While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world, the family must decide what they believe before all is lost.',
    popularity: 1392.352,
    poster_path: '/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg',
    release_date: '2023-02-01',
    title: 'Knock at the Cabin',
    video: false,
    vote_average: 6.4,
    vote_count: 1127
  },
  {
    adult: false,
    backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
    genre_ids: [28, 12, 878],
    id: 505642,
    original_language: 'en',
    original_title: 'Black Panther: Wakanda Forever',
    overview:
      'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
    popularity: 1371.053,
    poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
    release_date: '2022-11-09',
    title: 'Black Panther: Wakanda Forever',
    video: false,
    vote_average: 7.3,
    vote_count: 4301
  },
  {
    adult: false,
    backdrop_path: '/sGE6N1vJjxZLkOJEXdIOqTslxuL.jpg',
    genre_ids: [99],
    id: 1087040,
    original_language: 'en',
    original_title: 'Money Shot: The Pornhub Story',
    overview:
      'Featuring interviews with performers, activists and past employees, this documentary offers a deep dive into the successes and scandals of Pornhub.',
    popularity: 1162.821,
    poster_path: '/kUWTY8rwEZ3d8G31GuPMbvqS67D.jpg',
    release_date: '2023-03-15',
    title: 'Money Shot: The Pornhub Story',
    video: false,
    vote_average: 5.9,
    vote_count: 100
  },
  {
    adult: false,
    backdrop_path: '/7eccX0xay9pDj6ZQvU4cu3whw18.jpg',
    genre_ids: [16, 14, 27],
    id: 1003579,
    original_language: 'en',
    original_title: 'Batman: The Doom That Came to Gotham',
    overview:
      "Explorer Bruce Wayne accidentally unleashes an ancient evil, and returns to Gotham after being away for two decades. There, Batman battles Lovecraftian supernatural forces and encounters allies and enemies such as Green Arrow, Ra's al Ghul, Mr. Freeze, Killer Croc, Two-Face and James Gordon.",
    popularity: 1150.832,
    poster_path: '/hrATQE8ScQceohwInaMluluNEaf.jpg',
    release_date: '2023-03-10',
    title: 'Batman: The Doom That Came to Gotham',
    video: false,
    vote_average: 6.4,
    vote_count: 38
  },
  {
    adult: false,
    backdrop_path: '/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg',
    genre_ids: [28, 12, 53],
    id: 646389,
    original_language: 'en',
    original_title: 'Plane',
    overview:
      'After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.',
    popularity: 1127.811,
    poster_path: '/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg',
    release_date: '2023-01-12',
    title: 'Plane',
    video: false,
    vote_average: 6.9,
    vote_count: 963
  },
  {
    adult: false,
    backdrop_path: '/sRfX2XPjyL7nRKVRKXVG6D0bVQI.jpg',
    genre_ids: [27, 53],
    id: 884184,
    original_language: 'en',
    original_title: 'Consecration',
    overview:
      "After the alleged suicide of her priest brother, Grace travels to the remote Scottish convent where he fell to his death. Distrusting the Church's account, she uncovers murder, sacrilege and a disturbing truth about herself.",
    popularity: 1119.737,
    poster_path: '/txP5HTHAlwLV1ZieGKviCsnWhXS.jpg',
    release_date: '2023-02-09',
    title: 'Consecration',
    video: false,
    vote_average: 6.9,
    vote_count: 21
  },
  {
    adult: false,
    backdrop_path: '/muw9YsAsSd3DDRme2OEJJoVqun9.jpg',
    genre_ids: [53, 28],
    id: 850871,
    original_language: 'es',
    original_title: 'Sayen',
    overview:
      "Sayen is hunting down the men who murdered her grandmother. Using her training and knowledge of nature, she is able to turn the tables on them, learning of a conspiracy from a corporation that threatens her people's ancestral lands.",
    popularity: 1052.037,
    poster_path: '/aCy61aU7BMG7SfhkaAaasS0KzUO.jpg',
    release_date: '2023-03-03',
    title: 'Sayen',
    video: false,
    vote_average: 6.2,
    vote_count: 63
  },
  {
    adult: false,
    backdrop_path: null,
    genre_ids: [28, 80],
    id: 730629,
    original_language: 'en',
    original_title: 'John Wick: Chapter 5',
    overview:
      'The fifth instalment in the John Wick franchise, confirmed to be in development.',
    popularity: 970.346,
    poster_path: '/A1Z4TjH3xqu4rHwAgLM3LX89luC.jpg',
    title: 'John Wick: Chapter 5',
    video: false,
    vote_average: 0,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: '/r17jFHAemzcWPPtoO0UxjIX0xas.jpg',
    genre_ids: [28, 53, 80],
    id: 324552,
    original_language: 'en',
    original_title: 'John Wick: Chapter 2',
    overview:
      'John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.',
    popularity: 965.369,
    poster_path: '/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg',
    release_date: '2017-02-08',
    title: 'John Wick: Chapter 2',
    video: false,
    vote_average: 7.3,
    vote_count: 11142
  },
  {
    adult: false,
    backdrop_path: '/wybmSmviUXxlBmX44gtpow5Y9TB.jpg',
    genre_ids: [28, 35, 14],
    id: 594767,
    original_language: 'en',
    original_title: 'Shazam! Fury of the Gods',
    overview:
      'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
    popularity: 949.581,
    poster_path: '/3GrRgt6CiLIUXUtoktcv1g2iwT5.jpg',
    release_date: '2023-03-15',
    title: 'Shazam! Fury of the Gods',
    video: false,
    vote_average: 7,
    vote_count: 251
  },
  {
    adult: false,
    backdrop_path: '/pxJbfnMIQQxCrdeLD0zQnWr6ouL.jpg',
    genre_ids: [28, 35, 53],
    id: 1077280,
    original_language: 'en',
    original_title: 'Die Hart',
    overview:
      'Kevin Hart - playing a version of himself - is on a death-defying quest to become an action star. And with a little help from John Travolta, Nathalie Emmanuel, and Josh Hartnett - he just might pull it off.',
    popularity: 931.464,
    poster_path: '/1EnBjTJ5utgT1OXYBZ8YwByRCzP.jpg',
    release_date: '2023-02-22',
    title: 'Die Hart',
    video: false,
    vote_average: 6.2,
    vote_count: 216
  },
  {
    adult: false,
    backdrop_path: '/AsEgGeccI32SwMBkxpwhOkhbzmF.jpg',
    genre_ids: [28, 878, 53, 27],
    id: 1011679,
    original_language: 'en',
    original_title: 'Shark Side of the Moon',
    overview:
      'Decades ago, the USSR developed unkillable sharks and launched them to the moon. Today, a team of American astronauts will endure the fight of their lives.',
    popularity: 925.584,
    poster_path: '/v5CfpzxoJDkZxjZAizClFdlEF0U.jpg',
    release_date: '2022-08-12',
    title: 'Shark Side of the Moon',
    video: false,
    vote_average: 5.3,
    vote_count: 112
  },
  {
    adult: false,
    backdrop_path: '/rV54txX9Whz7o66qoPz0VDLTvUU.jpg',
    genre_ids: [18],
    id: 677179,
    original_language: 'en',
    original_title: 'Creed III',
    overview:
      'After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damien Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damien — a fighter who has nothing to lose.',
    popularity: 915.761,
    poster_path: '/vJU3rXSP9hwUuLeq8IpfsJShLOk.jpg',
    release_date: '2023-03-01',
    title: 'Creed III',
    video: false,
    vote_average: 7.1,
    vote_count: 433
  }
];
